### ISSUE TITLE
Wrong Files API base path

### ISSUE THREAD

**Issue by AmzDevelopmentTeam** [XeroAPI/Xero-Java#287] opened 2021-05-27 23:52 UTC
Files API is setting the base path "https://api.xero.com/api.xro/2.0", but the correct base path for Files API is "https://api.xero.com/files.xro/1.0".

Here's where the default base path is set
https://github.com/XeroAPI/Xero-Java/blob/c724692bfaf50558403a6bc3bf48ce29ab6f4655/src/main/java/com/xero/api/ApiClient.java#L49

And where the incorrect Files path is set
https://github.com/XeroAPI/Xero-Java/blob/c724692bfaf50558403a6bc3bf48ce29ab6f4655/src/main/java/com/xero/api/client/FilesApi.java#L1589

**Comment by rdemarco-xero** [comment] 2021-07-15 18:37
Hi @AmzDevelopmentTeam, thanks for digging into this. You are correct that the default ApiClient will result in the incorrect base path for the Files API. We'll take a look at this to see if something should be changed but in the meantime you could implement the following:

```
        // Init Files client
        ApiClient defaultFilesClient = new ApiClient("https://api.xero.com/files.xro/1.0",null,null,null,null);
        // Get Singleton - instance of files client
        filesApi = FilesApi.getInstance(defaultFilesClient);
```
An example of this approach can be found [here in our Java sample app](https://github.com/XeroAPI/xero-java-oauth2-app/blob/master/src/com/xero/app/AuthenticatedResource.java#L285-L318).

**Comment by rdemarco-xero** [comment] 2021-07-22 17:28
Closing this issue because the SDK is working as designed. An example of how to instantiate the client with the proper url can be found in our sample app [here](https://github.com/XeroAPI/xero-java-oauth2-app/blob/master/src/com/xero/app/AuthenticatedResource.java#L285-L318).

If you are still experiencing issues please re-open this ticket.

**Closed by rdemarco-xero** 2021-07-22 17:28 UTC
