### ISSUE TITLE
Request for Jakarta platform compliant Xero SDK

### ISSUE THREAD

**Issue by liuyng0** [XeroAPI/Xero-Java#354] opened 2023-11-06 05:31 UTC
The Xero-Java currently has a dependency on the deprecated javax.servlet, which should be replaced by jarkata.* for jakarta platform compliant: https://jakarta.ee/blogs/javax-jakartaee-namespace-ecosystem-progress/ ,
https://github.com/XeroAPI/Xero-Java/blob/32425e4f71cc7223aded8d6bfec3c452bcee4009/pom.xml#L73-L77
https://github.com/search?q=repo%3AXeroAPI%2FXero-Java+javax&type=code

We are proactively removing such deprecated dependencies, so cannot use the SDK with javax.* as dependency. Please help to release jarkata compliance SDK. Thanks!

**Comment by dalli98** [comment] 2024-02-08 11:19
@juTru I solved this issue by using the following dependency in pom.xml

<dependency>
	<groupId>com.github.xeroapi</groupId>
	<artifactId>xero-java</artifactId>
	<version>4.29.1</version>
	<exclusions>
		<exclusion>
			<groupId>org.glassfish.jersey.core</groupId>
			<artifactId>jersey-client</artifactId>
		</exclusion>
		<exclusion>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-multipart</artifactId>
		</exclusion>
		<exclusion>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-json-jackson</artifactId>
		</exclusion>

		<exclusion>
			<groupId>org.glassfish.jersey.core</groupId>
			<artifactId>jersey-common</artifactId>
		</exclusion>
		<exclusion>
			<groupId>org.glassfish.jersey.ext</groupId>
			<artifactId>jersey-entity-filtering</artifactId>
		</exclusion>
	</exclusions>
</dependency>
<dependency>
	<groupId>org.glassfish.jersey.core</groupId>
	<artifactId>jersey-client</artifactId>
	<version>2.27</version>
</dependency>
<dependency>
	<groupId>org.glassfish.jersey.media</groupId>
	<artifactId>jersey-media-multipart</artifactId>
	<version>2.27</version>
</dependency>
<dependency>
	<groupId>org.glassfish.jersey.media</groupId>
	<artifactId>jersey-media-json-jackson</artifactId>
	<version>2.27</version>
</dependency>
<dependency>
	<groupId>org.glassfish.jersey.core</groupId>
	<artifactId>jersey-common</artifactId>
	<version>2.27</version>
</dependency>
<dependency>
	<groupId>org.glassfish.jersey.ext</groupId>
	<artifactId>jersey-entity-filtering</artifactId>
	<version>2.27</version>
</dependency>

**Comment by dalli98** [comment] 2024-02-08 11:20
It looks like xeroapi wants to use jersey 2.27. However, the property is overridden and it uses a newer version which is not compatible

**Comment by denysboiko** [comment] 2024-03-21 19:56
Hi! I can see that this issue has been addressed in [4.30.1](https://github.com/XeroAPI/Xero-Java/releases/tag/4.30.1) but it is not available on https://mvnrepository.com/artifact/com.github.xeroapi/xero-java. Do you have any plans for publishing it on Maven Central?

Thanks!

**Comment by manishT72** [comment] 2024-05-02 17:20
Issue should be fixed now in release [5.0.0](https://github.com/XeroAPI/Xero-Java/releases/tag/5.0.0).

**Comment by manishT72** [comment] 2024-09-19 05:58
Closing the ticket since the issue is fixed.

**Closed by manishT72** 2024-09-19 05:58 UTC
